import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { NavBar } from "@/components/ui/nav-bar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kite Lite",
  description: "Generated by JVT",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavBar />

        <div className="flex items-center justify-center h-dvh">
          <div className="flex justify-center gap-4 flex-col items-center">
            <h1 className="text-5xl font-bold">Weather you like it or not</h1>

            {children}
            <p className="mt-8">&copy; JVT</p>
          </div>
        </div>

        <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}
